### ISSUE TITLE
TypeAlias for RecordType and EnumType

### ISSUE THREAD

**Issue by Shard** [sanctuary-js/sanctuary-def#113]
When I'm using RecordTypes or EnumTypes (espicially both together) I find that their debug output can be hard to read and i'm finding myself having to parse through lines of an overflowing signature to match in my head what I know as a type.

For example, I have a function like:

```purescript
viewResource :: ResourceType -> Maybe Resource
```

So instead of having an error like:

```purescript
     TypeError: Invalid value

viewResource :: ("gold" | "knowledge" | "wood" | "stone" | "food") -> Maybe { cost :: ("gold" | "knowledge" | "wood" | "stone" | "food"), name :: String, on :: Boolean, description :: String, created :: Date }
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The value at position 1 is not a member of ‘Maybe { cost :: ("gold" | "knowledge" | "wood" | "stone" | "food"), name :: String, on :: Boolean, description :: String, created :: Date }’.

```

We could apply a TypeAlias of **ResourceType** to the Enum ResourceType and get something like:

```purescript
     TypeError: Invalid value

viewResource :: ResourceType -> Maybe { cost :: ResourceType, name :: String, on :: Boolean, description :: String, created :: Date }
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The value at position 1 is not a member of ‘Maybe { cost :: ResourceType, name :: String, on :: Boolean, description :: String, created :: Date }’.
```

And further applying the alias of **Building** to RecordType:

```purescript
     TypeError: Invalid value

viewResource :: ResourceType -> Maybe Building
                                ^^^^^^^^^^^^^^

The value at position 1 is not a member of ‘Maybe Building’.
```

I could see there being issues potentially with stripping out the details of records completely when it comes to debugging which row in the record failed on (Although I think that's still in the works #75)

**Comment by Shard** [comment]
I just noticed #111 which fixes it for enums :tada: . Would it be possible to consider this for **RecordType** as well @davidchambers ?

**Comment by davidchambers** [comment]
I'm not sure I'm willing to give up the specificity provided by error messages for invalid record fields. Consider this example:

```javascript
dist({x: 0, y: null});
// ! TypeError: Invalid value
//
//   dist :: { x :: Number, y :: Number } -> { x :: Number, y :: Number } -> Number
//                               ^^^^^^
//                                 1
//
//   1)  null :: Null
//
//   The value at position 1 is not a member of ‘Number’.
//
//   See https://github.com/sanctuary-js/sanctuary-def/tree/v0.8.0#Number for information about the Number type.
```

I find the underlining of the offending field quite helpful.

It's worth noting that the behaviour you desire is already attainable by using a record type to define a nullary type. For example:

```javascript
//  Point :: Type
var Point = $.NullaryType(
  'my-package/Point',
  'http://example.com/my-package#Point',
  $.RecordType({x: $.Number, y: $.Number})._test
);

//  dist :: Point -> Point -> Number
var dist = def('dist', {}, [Point, Point, $.Number], function(p, q) {
  return Math.sqrt(Math.pow(p.x - q.x, 2) + Math.pow(p.y - q.y, 2));
});

dist({x: 0, y: null});
// ! TypeError: Invalid value
//
//   dist :: Point -> Point -> Number
//           ^^^^^
//             1
//
//   1)  {"x": 0, "y": null} :: Object, StrMap ???
//
//   The value at position 1 is not a member of ‘Point’.
//
//   See http://example.com/my-package#Point for information about the my-package/Point type.
```

**Comment by Shard** [comment]
I agree it would probably be better to have records show their incorrect value. The solution you provided would definitely fix the issues I'm having with records polluting my Error outputs, thanks!

**Comment by davidchambers** [comment]
> The solution you provided would definitely fix the issues I'm having with records polluting my Error outputs

That's good to hear. Let's see how much we like #111 in practice. If we love it we can reconsider supporting named record types in a less roundabout fashion.
