### ISSUE TITLE
Fix the inconsistent type of "env"

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary-def#123]
* [gitter/sanctuary#58aebbeae961e53c7f5762af](https://gitter.im/sanctuary-js/sanctuary?at=58aebbeae961e53c7f5762af)
* https://github.com/sanctuary-js/sanctuary-def/pull/121#discussion_r102713670

**Comment by Avaq** [comment]
One of the ideas was to replace all type constructors (`Type... -> Type`) in `env` with types that have already been applied with `Unknown`s, eg: `env.concat([Maybe(Unknown), Either(Unknown, Unknown)])`.

My concern is that currently, type constructors might actually be used by `sanctuary-def` in order to create concrete types for values with variable types, otherwise, what's the value of having these type constructors in the environment in the first place?

**Comment by davidchambers** [comment]
Thanks for opening this issue, Aldwin.

> otherwise, what's the value of having these type constructors in the environment in the first place?

So that values such as `[1, 2, 3]` and `Just('foo')` are recognized. For example:

```javascript
const a = $.TypeVariable('a');

$.create({checkTypes: true, env: [$.Number]})('id', {}, [a, a], x => x)([1, 2, 3]);
// ! TypeError: Type-variable constraint violation
//
//   id :: a -> a
//         ^
//         1
//
//   1)  [1, 2, 3] ::
//
//   Since there is no type of which all the above values are members, the type-variable constraint has been violated.
```

**Comment by Avaq** [comment]
> So that values such as `[1, 2, 3]` and `Just('foo')` are recognized

But wouldn't adding `Maybe(Unknown)` to the env instead of `Maybe` make the type-checker think that `Just(1)` and `Just('foo')` are consistent? Or is some other mechanism used to determine consistency over multiple occurrences of the same type-var?

**Comment by davidchambers** [comment]
`$.Unknown` is special. Search the code for `UNKNOWN` and you'll find several occurrences.

`$.Unknown` is used internally when the actual type cannot be completely determined. The type of `[]`, for example, is `Array Unknown`. `$.Array($.Unknown)` constrains the outer type without constraining the inner type.

`$.Unknown` is a bit like a stem cell. :)

**Comment by Avaq** [comment]
Oh, hold on a second! The type constructors are [discarded the moment they are passed](https://github.com/sanctuary-js/sanctuary-def/blob/master/index.js#L2354) into Sanctuary Def!

That clears everything up. Sanctuary Def simply doesn't use them.

**Comment by davidchambers** [comment]
Yes. What I'm suggesting is that it should be the caller's responsibility to do something like `S.EitherType($.Unknown, $.Unknown)` rather than for sanctuary-def to take care of it.

**Comment by Avaq** [comment]
Totally get that now. This change wouldn't even impact the user much, as most of the changes would happen in the internals. It would be a major version for `sanctuary-def`, but a minor or even patch for `sanctuary`.

Come to think of it. It would be a patch for `sanctuary-def` as well, if we wouldn't publish #121!

**Comment by Avaq** [comment]
We would simply remove the [`applyParameterizedTypes` line](https://github.com/sanctuary-js/sanctuary-def/blob/master/index.js#L1208) from `test`, which makes it compatible with the signature originally assigned to it before #121. Nothing changes on the surface.

**Comment by Avaq** [comment]
And then it's just `S.env` that needs a quick patch.

**Comment by davidchambers** [comment]
Okay. Let's remove `applyParameterizedTypes`, release `sanctuary-def@1.0.0`, then open a Sanctuary pull request to update its sanctuary-def dependency and `S.env`. Does this sound good?

**Comment by Avaq** [comment]
Sounds good. I suppose we can close #121 then. Haha, my eagerness to get a patch out actually caused me to have to wait longer.

**Comment by Avaq** [comment]
Oh wait. If you're going to release this as major, we may as well merge #121 so that people will not get :bug: bitten in the current version. I don't know.

**Comment by davidchambers** [comment]
> Oh wait. If you're going to release this as major, we may as well merge #121 so that people will not get :bug: bitten in the current version.

This seems reasonable.

I'm about to put my head down. I'll come back to these issues and pull requests on Saturday. :)

**Comment by Avaq** [comment]
After collecting my thoughts, this is what I think we should do:

* Patch `sanctuary` to export an `env` which is strictly `Array Type`, immediate fixing the issue at hand.
* Close #121 
* Open PRs in `sanctuary-def` to:
  1. Remove the unnecessary call to `applyParameterizedTypes`
  1. Document how to apply parameterized types in order to create a valid `env`
* Possibly release the aforementioned changes to `sanctuary-def` under a new major version. There's no hurry anymore since we patched the problem in `sanctuary`.
