### ISSUE TITLE
Add $.Symbol

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary-def#133]
In https://github.com/sanctuary-js/sanctuary/issues/381 I mentioned that `R.pluck` works with Arrays and Number indices as opposed to just StrMaps and String keys.

The signature of `S.pluck` _could_ be:
```hs
type Natural = PositiveInteger | 0

type AccessibleKey = String | Natural | Symbol

pluck :: (Accessible a, Functor f) => AccessibleKey -> f a -> f b
```

This would require `$.Symbol` (and possibly `$.Natural`).

**Comment by davidchambers** [comment]
@gabejohnson, I prefer to think of array keys as `'0'`, `'1'`, `'2'`, … rather than `0`, `1`, `2`, …, since `xs[0]` is the implicit equivalent of `xs[String(0)]`.

Regardless of the motivation, defining `$.Symbol` is a good idea. Would you like to open a pull request for this?
