### ISSUE TITLE
Named Record Types

### ISSUE THREAD

**Issue by JAForbes** [sanctuary-js/sanctuary-def#138]
I work with a lot of objects, it'd be helpful to tag them with a name.  It'd make for more terse signatures.

I still think we should show the complete interface if a type error occurs though.  But when rendering the signature, it'd be preferable to just use the name, I'm finding type errors nearly always wrap the terminal/repl because I'm working with large records.

Then the `^^^^` don't line up with the particular argument, so its not immediately obvious what is causing it to fail.

**Comment by davidchambers** [comment]
Good idea.

An idea that just occurred to me is to have the representation span multiply lines:

```
{
  bar :: Array String
  baz :: {
    quux :: Integer
            ^^^^^^^
               1
  }
  foo :: Boolean
}
```

As opposed to:

```
{ bar :: Array String, baz :: { quux :: Integer }, foo :: Boolean }
                                        ^^^^^^^
                                           1
```

We could use the name of the record type in the signature, then expand the type in the description below and underline the invalid portion.

**Comment by JAForbes** [comment]
That'd be fantastic!

**Comment by kurtmilam** [comment]
It'd be great to have the representation span multiple lines. I have some records that wrap even on a 4K monitor :D

**Comment by JAForbes** [comment]
Some new thoughts: 

I'm using this to validate API responses and there are a lot of fields, sometimes its hard to see what is wrong with a value when there are 50 keys with various levels of nesting.

It's not that useful to render the complete type for large objects (say keys > 5, or levels of nesting greater than 2).  It'd be a lot more useful to me to list the paths and types that were invalid, with the expected type and the actual value.  Particularly when there are multiple validation issues.

```
TypeError ... yada

1. Value -123 at path: a.b.c.d is not a member of PositiveNumber
2. Value [1,2,3] at path: a.b.c.e is not a member of List String
```

It could also be handy to show the values in context, with the valid values filtered out.

```
TypeError Provide value did not satisfy custom RecordType API Response

The provided value did not satisfy the following Type constraints:

Preview:

  { a: 
    { b: 
      { c: 
         { d: -123, e: [1,2,3] }, ... 
       }, ... 
     }, ... 
  } 

1. Value -123 at path: a.b.c.d is not a member of PositiveNumber
2. Value [1,2,3] at path: a.b.c.e is not a member of List String
```

It'd be great too if validate, or something similar could provide this metadata as an object of the form: `{ preview :: String, failures:: List { value:: Any, path: List String, type: Type } }`

That way libraries like sum-type (and hopefully others) could build domain specific error messages without recreating a lot of what sanctuary-def already does very well.

**Comment by davidchambers** [comment]
Nice idea, @JAForbes. What's unclear to me is how the approach of just displaying the path to the type error would work for nested types which aren't exclusively *record* types. Imagine a type such as `Future Error { x :: Maybe { y :: Either String { z :: Array Number } } }`.

**Comment by JAForbes** [comment]
Yeah not sure either.  Perhaps in that example if the error was with the Array we can summarise the surrounding structure that isn't on a direct path to the value.

```js
Value `[ 'hello', 'world' ] does not satisfy the Array Number type constraint.


at Future > { x } > Maybe> { y } > Either ... Array Number
                                                   ^^^^^^^
in Future.Resolved( Maybe.Just( Either.Right([1,2,3]) ) )
```

The structure could start with the offending value, and the constraint(s) it did not meet.

Then a shorthand (that could be improved) to indicate how deeply nested the value was without rendering values that are valid or unrelated to the error.  I'm using `{ x } > Maybe > { y }` instead of `{ x:: Maybe { y:: } }` because it can quickly become difficult to match parens and identify the particular path our invalid value resides at.

```
at Future > { x } > Maybe> { y } > Either ... Array Number
                                                   ^^^^^^^
```

It maybe could be replace with the more traditional Javascript `.` but I think that could be confusing because the path isn't literally `Future.x.Maybe.y`.

And finally, a complete rendering of the complete structure.  

```js
in Future.Resolved( Just( Right([1,2,3]) ) )
```

And I think it'd be great if RecordTypes in particular omitted sibling values here, despite the above notation.  In my case at least the complete rendering of the record type displaces the more helpful information about the specific value that failed.  I rarely look at the complete output now because it would take me to long to mentally parse for large objects.
