### ISSUE TITLE
Prototypical Record Types?

### ISSUE THREAD

**Issue by JAForbes** [sanctuary-js/sanctuary-def#141]
Currently `$.RecordType` checks a value via `Object.keys`.  `Object.keys` will not pick up prototypical properties and methods.

I think it'd be pretty helpful to be able to define types that include prototypes.

E.g.

```
const $Promise = 
  $.RecordType({
    then: $.AnyFunction
    ,catch: $.AnyFunction
  })
```

Maybe `$Promise` isn't the best example, we'd probably want to use a BinaryType in that case.  But even internally we could use the above in the validator for a BinaryType version for brevity.

**Comment by davidchambers** [comment]
I agree. The Sanctuary way seems to be to respect enumerable keys, regardless of where they're defined. Would you like to submit a pull request for this change, James?

**Comment by JAForbes** [comment]
Yeah sure 😄

**Comment by davidchambers** [comment]
#164:

> It would be a shame not to support prototypal inheritance, as I consider it one of the good parts of JavaScript. I suggest we state that _a field is an enumerable property_. Note that this means that `Promise.resolve(42)` is not a member of `$.RecordType({then: $.AnyFunction})` as @JAForbes requested in #141. I can live with this. One could define an equivalent type via `$.NullaryType` (or even `$.UnaryType`).
