### ISSUE TITLE
Unnecessary Invocations Of Type#test Functions

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary-def#16]
I noticed something strange last night, it seems that type checking is performed for every type in the environment for a function regardless of whether that type is part of a function's type signature or not.

E.g.,
```js
const $test = $.NullaryType(
  'TEST',
  x => typeof x === 'number'
);

const $notUsed = $.NullaryType(
  'NOTUSED',
  x => {
    console.log('Why am I being used?');
    return typeof x === 'string'
  }
);

const env = $.env.concat([$test, $notUsed]);
const def = $.create(env);

const f = def('f', {}, [$test, $test], x => x + 1);
f(1);
// Why am I being used?
// Why am I being used?
```

If I put a `console.log` in `NullaryType`'s `test` function I see that there is an invocation for each one of those types too and I'm guessing for any other. This seems quite wasteful to me and possibly a source of confusion. In fact, the only reason I found this issue was because I was getting this cryptic error message for a custom type I'd defined which I realised, after much investigation, had a `test` function with a call that caused one of the built in types to throw even though I wasn't using that type.

**Comment by davidchambers** [comment]
Thanks for raising this issue, Stefano.

Given an argument `x`, we currently consult all the types in the environment to see which contain `x`. We then see whether any of these types are compatible with the expected type. It would be interesting to see whether we could limit our search based on the expected type. This may be fruitful, but I suspect many internal changes would be required. This is something we could revisit once we've addressed the more pressing concerns.

**Comment by svozza** [comment]
Yeah, sounds good.

**Comment by davidchambers** [comment]
@rsabb, this is the place to start if you're interested in improving performance. :)
