### ISSUE TITLE
Can RecordType contains optional parameters?

### ISSUE THREAD

**Issue by arrterian** [sanctuary-js/sanctuary-def#168]
Hello!
I have a code like following:

```javascript
const fetch = def(
  'fetch',
  {},
  [
    CollectionType,
    $.RecordType({
      query: $.Object,
      skip: $.Number,
      limit: $.Number,
    }),
    $.Object,
    $.Unknown,
  ],
  (collectionName, { query, skip, limit }, db) =>
    Future.node(done => {
      // eslint-disable-next-line
      let findReq = db.collection(collectionName).find(query)

      // eslint-disable-next-line
      findReq = skip ? findReq.skip(skip) : findReq
      // eslint-disable-next-line
      findReq = limit ? findReq.limit(limit) : findReq

      return findReq.toArray(done)
    })
)
```

Can i make parameters skip and limit optional?

**Comment by davidchambers** [comment]
> Can i make parameters skip and limit optional?

The idiomatic approach is to use the Maybe type:

```javascript
//    QueryOpts :: Type
const QueryOpts = $.RecordType({
  query: $.StrMap($.String),
  skip: S.MaybeType($.Number),
  limit: S.MaybeType($.Number),
});
```

This code would need to change:

```javascript
findReq = skip ? findReq.skip(skip) : findReq
```

This should work:

```javascript
findReq = S.fromMaybe(findReq, findReq.skip.bind(findReq), skip)
```

**Comment by Avaq** [comment]
> The idiomatic approach is to use the Maybe type

I think in this case that would make for a bit of a verbose API. Instead of this:

```js
fetch({query: {name: 'bob'}})
```

One would have to do:

```js
fetch({query: {name: 'bob'}, skip: S.Nothing, limit: S.Nothing})
```

I would probably create two functions, `fetch` and `fetchRange`, the latter taking `skip` and `limit` as required integers, the first just having a query. I'm not a fan of optional parameters, named or unnamed.

**Comment by davidchambers** [comment]
> I would probably create two functions, `fetch` and `fetchRange`, the latter taking `skip` and `limit` as required integers

I like this approach. :)
