### ISSUE TITLE
Performance problem 

### ISSUE THREAD

**Issue by arrterian** [sanctuary-js/sanctuary-def#170]
I wrote a small library with sunctuary-def and sanctuary and was a little wondered when saw my test time execution.

Let's see on the test:
```javascript
  it('send list messages', (done) => {
    const instance = new OriginSQS();
    const stub = sinon.stub().yields(null, {
      // moks for aws response
    });

    instance.sendMessageBatch = stub;

    SQS.sendMessages({ instance, queueUrl }, [
       // list of messages for sending
    ])
      .fork(
        () => done(new Error('should call never')),
        (result) => {
          const expectedArgs = {
            QueueUrl: queueUrl,
            Entries: [
              { Id: "id1", ReceiptHandle: 'recp1', MessageBody: '{ v: "body1" }' },
              { Id: "id2", ReceiptHandle: 'recp2', MessageBody: '{ v: "body2" }' },
              { Id: "id3", ReceiptHandle: 'recp3', MessageBody: '{ v: "body3" }' },
            ],
          };

          const expctedReuslt = [
            'Right({"messageId": "id1"})',
            'Left({"errorCode": "TEST_ERROR_WITHOUT_MESSAGE", "isMessageBad": true, "messageId": "id2", "reason": "Unknown error"})',
            'Left({"errorCode": "TEST_ERROR", "isMessageBad": false, "messageId": "id3", "reason": "Failed for test"})',
          ];
          const actualResult = S.map(S.toString, result);

          assert.isTrue(stub.calledOnce, 'should be called only once');
          assert.deepEqual(stub.args[0][0], expectedArgs, 'bad argumments for sendMessageBatch method')
          assert.deepEqual(actualResult, expctedReuslt, 'should return all ids wraped in Right');
          done();
        }
      );
  });
```

The test is testing following function:
```javascript
// sendMessages :: ActionOptsType -> MessageType -> FutureType(Error, Unknown)
const sendMessages = def(
  'sendMessages', {},
  [
    Types.ActionOptsType,
    $.Array(Types.MessageType),
    FutureType($.Error, $.Array(S.EitherType(Types.FailureBatchType, Types.SuccessBatchType))),
  ],
  (sqs, messages) => {
    const sendParams = {
      QueueUrl: sqs.queueUrl,
      Entries: S.map(formatSendRequest, messages),
    };

    return S.equals(messages.length, 0)
      ? Future.of([])
      : Future.node(done => sqs.instance.sendMessageBatch(sendParams, done))
        .map(formatBatchResult);
  }
);
```
Function `formatSendRequest` and `formatBatchResult` also defined with sunctuary-def and contains type cheking.

Time execution of the test:
 * with enabled type checking: *603ms*
 * without disabled type checking: *very fast (can't track the time)*

Have you planned to increase the productivity of `sanctuary-def`?
Is some best practice exist for using sunctuary-def? (maybe I shouldn't write types for everything)

**Comment by davidchambers** [comment]
> Have you planned to increase the productivity of `sanctuary-def`?

I'm sure there's plenty of room for performance improvements, but there's no avoiding the fact that to assert that a value is of type `Array String` it's necessary to perform 1001 checks if the array contains 1000 elements (one for the container; one for each of the elements).

> Is some best practice exist for using sunctuary-def?

Because run-time type checking affects performance you may decide to disable type checking in production. This way you can benefit from the informative error messages during development and testing without negatively affecting your users.

For Node I suggest:

```javascript
const def = $.create({
  checkTypes: process.env.SANCTUARY_CHECK_TYPES === 'true',
  env: $.env,
});
```

During development:

```console
$ SANCTUARY_CHECK_TYPES=true node myapp.js
```

In production:

```console
$ SANCTUARY_CHECK_TYPES=false node myapp.js
```

You could instead switch based on `NODE_ENV`, but in my experience it's useful to be able to toggle run-time settings independently.
