### ISSUE TITLE
Partial record type proposal

### ISSUE THREAD

**Issue by arrterian** [sanctuary-js/sanctuary-def#175]
I write code with sunctuary-def about 1 month and pay attention to that I often need partial record type. For example:

I have some detail described record:

```javascript
const UserType = $.RecordType({
  firstName: $.String,
  lastName: $.String,
  bio: $.String,
  ...
});
```

For functions that work with firstName and lastName, I don't need pass all record. I need only record that contains first and last name.

```javascript
const UserNamesType = $.RecordType({
  firstName: $.String,
  lastName: $.String,
});

const getUserFullName = def('getUserFullName', {},
  [UserNamesType, $.String],
  user => S.concat(user.firstName, user.lastName);
);
```

Now we can pass to function full user object or partial if we don't have enough of data.
Will be useful if we had a helper as this:

```haskell
getPartialRecord :: RecordType a, b => Array(String) -> a -> b
```

And now we can make partial record by this way:

```javascript
const UserNamesType = getPartialRecord(['firstName', 'lastName'], UserType);
```

**Comment by davidchambers** [comment]
It's not clear to me whether sanctuary-def should support additive creation of record types, subtractive creation of record types (as proposed in this issue), or both.

I see value in the function you've proposed. For now I suggest defining it in your own project, as I'm not yet convinced it warrants inclusion in sanctuary-def itself. Here's a possible implementation:

```javascript
function getPartialRecord(fields, type) {
  var types = {};
  for (var idx = 0; idx < fields.length; idx += 1) {
    var name = fields[idx];
    types[name] = type.types[name].type;
  }
  return $.RecordType(types);
}
```
