### ISSUE TITLE
TypeError: Invalid value when using S.is and sanctuary-def

### ISSUE THREAD

**Issue by cdbkr** [sanctuary-js/sanctuary-def#226]
I am playing around with these two packages:
 - sanctuary@0.15.1 as S
 - sanctuary-def@0.19.0 as $

and with a simple pipe:
```
S.pipe([
  S.parseJson(S.is($.String))
])
('true')
```
I am receiving this error:
TypeError: Invalid value

```
is :: Type -> Any -> Boolean
      ^^^^
       1

1)  String ::

The value at position 1 is not a member of ‘Type’.

See https://github.com/sanctuary-js/sanctuary-def/tree/v0.18.1#Type for information about the Type type.
```
I am experiencing this with Replem, but also on Repl.it. Anything wrong with what I am doing or something in the used packages by sanctuary?

**Comment by davidchambers** [comment]
There's no guarantee that the latest versions of `sanctuary` and `sanctuary-def` are compatible. The prudent approach is to use the version of `sanctuary-def` upon which `sanctuary` itself depends.

<https://github.com/sanctuary-js/sanctuary/blob/v0.15.1/package.json#L17>:

> ```json
>     "sanctuary-def": "0.18.1",
> ```

Let me know whether depending on `sanctuary-def@0.18.1` resolves the issue. :)

**Comment by cdbkr** [comment]
Thanks @davidchambers for the clarification :) Indeed with:
 - sanctuary@0.15.1 as S
 - sanctuary-def@0.18.1 as $
It works fine.
Will next version of _sanctuary_  be aligned to latest _sanctuary-def_ ?

**Comment by davidchambers** [comment]
I'm pleased that things are working now. :)

> Will next version of _sanctuary_  be aligned to latest _sanctuary-def_ ?

Yes, it will.
