### ISSUE TITLE
type check non-function values

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary-def#34]
Why are functions the only values to get :heart: from sanctuary-def?

I often indicate the type of a non-function value. For example:

```javascript
//    words :: [String]
const words = [
  'foo',
  'bar',
  'baz',
];
```

It seems natural to me for sanctuary-def to enforce this:

```javascript
//    words :: [String]
const words =
def('words',
    {},
    [$.Array($.String)],
    ['foo',
     'bar',
     'baz']);
```

In this trivial example the type checking provides no value, but with more complex types it could be useful. Another use case is verifying that data which lives elsewhere is of the expected shape:

```javascript
//    stateMap :: StrMap String
const stateMap =
def('stateMap',
    {},
    [$.StrMap($.String)],
    require('./states.json'));
```

If __states.json__ is `{"AL": "Alabama", …, "WY": "Wyoming"}`, the code above would be equivalent to `const stateMap = require('./states.json');`. If, though, the shape of the data does not align with our expectations we'd get a descriptive run-time error:

    ‘stateMap’ is expected to be a member of (StrMap String); ["AL", …, "WY"] is not

The one downside is that we'd lose the ability to describe nullary functions. We could provide two functions: one for defining functions; one for defining non-function values. These could be named `defn` and `def` respectively. `def` (or whatever we were to name it) would take `Type` rather than `[Type]` as its third argument.

**Comment by davidchambers** [comment]
> The one downside is that we'd lose the ability to describe nullary functions.

Supporting nullary functions is more important than supporting non-function values.

One could even define a nullary function and apply it immediately to produce the value:

```javascript
//    stateMap :: StrMap String
const stateMap =
def('stateMap', {}, [$.StrMap($.String)], () => require('./states.json'))();
```

**Comment by safareli** [comment]
you could also define `defVal = (a,b,c,d) => def(a, b, c, () => d)()`

**Comment by davidchambers** [comment]
Excellent point, @safareli. :)
