### ISSUE TITLE
Add union type to sanctuary-def

### ISSUE THREAD

**Issue by jgoux** [sanctuary-js/sanctuary-def#60]
Hello,
would it be possible to add union type to sanctuary-def ?

Other related projects :  
- https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-union-combinator
- https://github.com/gcanti/tcomb/blob/master/docs/API.md#pattern-matching-the-match-function
- https://github.com/paldepind/union-type#union-type

**Comment by davidchambers** [comment]
I'd love to know more about what you have in mind, @jgoux.

Are you thinking we could provide pattern matching, so a function needn't determine which "tag" it is dealing with? If so, how do you imagine the following definition might change?

```javascript
S.either =
def('either',
    {},
    [$.Function, $.Function, $Either(a, b), c],
    function(l, r, either) {
      return either.isLeft ? l(either.value) : r(either.value);
    });
```

**Comment by davidchambers** [comment]
Closing in favour of sanctuary-js/sanctuary-union-type#1

**Comment by rockymadden** [comment]
As a note to anyone else looking for this as well, the repo seems to be: https://github.com/JAForbes/sum-type
